#![expect(
    clippy::inline_always,
    clippy::ref_as_ptr,
    reason = "The COM adapter generated by windows_core::implement triggers these lints."
)]

use std::{
    ffi::OsString,
    os::windows::ffi::OsStringExt,
    path::Path,
    sync::{Arc, Mutex},
};
use windows::Win32::{
    Foundation::E_FAIL,
    System::Com,
    UI::Shell::{
        IFileOperationProgressSink, IFileOperationProgressSink_Impl, IShellItem,
        SIGDN_DESKTOPABSOLUTEPARSING,
    },
};
use windows_core::{HRESULT, PCWSTR, PWSTR, Ref, implement};

use crate::{Error, Result};

#[derive(Debug)]
struct ShellAllocatedString(PWSTR);

impl ShellAllocatedString {
    fn new(shell_item: &IShellItem) -> windows_core::Result<Self> {
        // SAFETY: `shell_item` remains valid for the duration of this call and the
        // returned string pointer is released by `ShellAllocatedString::drop`.
        let pointer = unsafe { shell_item.GetDisplayName(SIGDN_DESKTOPABSOLUTEPARSING)? };
        if pointer.is_null() {
            return Err(windows_core::Error::new(
                E_FAIL,
                "Shell returned a null display name for the recycled item",
            ));
        }

        Ok(Self(pointer))
    }

    fn into_os_string(self) -> OsString {
        // SAFETY: `ShellAllocatedString` is constructed from a non-null
        // `GetDisplayName` pointer, which is a NUL-terminated UTF-16 string.
        let display_name_wide = unsafe { self.0.as_wide() };

        OsString::from_wide(display_name_wide)
    }
}

impl Drop for ShellAllocatedString {
    fn drop(&mut self) {
        // SAFETY: `ShellAllocatedString::new` stores the pointer returned by
        // `GetDisplayName` and this is the only place that releases it.
        unsafe {
            Com::CoTaskMemFree(Some(self.0.as_ptr().cast::<std::ffi::c_void>()));
        }
    }
}

#[derive(Debug, Default)]
enum RecycleProgressState {
    #[default]
    Pending,
    Recycled {
        item_id: OsString,
    },
    Failed {
        message: String,
    },
}

fn record_progress_failure(
    state: &Arc<Mutex<RecycleProgressState>>,
    failure: impl Into<String>,
) -> windows_core::Result<()> {
    let mut state = state.lock().map_err(|source| {
        windows_core::Error::new(
            E_FAIL,
            format!("Recycle progress state was poisoned while recording failure: {source}"),
        )
    })?;

    *state = RecycleProgressState::Failed {
        message: failure.into(),
    };

    Ok(())
}

#[implement(IFileOperationProgressSink)]
#[derive(Debug)]
pub(super) struct RecycleProgressSink {
    state: Arc<Mutex<RecycleProgressState>>,
}

impl RecycleProgressSink {
    pub(super) fn new() -> Self {
        Self {
            state: Arc::new(Mutex::new(RecycleProgressState::default())),
        }
    }

    pub(super) fn to_file_operation_progress_sink(&self) -> IFileOperationProgressSink {
        Self {
            state: Arc::clone(&self.state),
        }
        .into()
    }

    pub(super) fn failure_message(&self) -> windows_core::Result<Option<String>> {
        let state = self.state.lock().map_err(|source| {
            windows_core::Error::new(
                E_FAIL,
                format!("Recycle progress state was poisoned while reading failure: {source}"),
            )
        })?;

        match &*state {
            RecycleProgressState::Failed { message } => Ok(Some(message.clone())),
            _ => Ok(None),
        }
    }

    pub(super) fn recycled_item_id(&self, path: &Path) -> Result<OsString> {
        let state = self.state.lock().map_err(|source| Error::Platform {
            message: format!(
                "Recycle progress state was poisoned for {}: {source}",
                path.display()
            ),
        })?;

        match &*state {
            RecycleProgressState::Pending => Err(Error::Platform {
                message: format!(
                    "Windows did not return a recycled shell item for {}",
                    path.display()
                ),
            }),
            RecycleProgressState::Recycled { item_id } => Ok(item_id.clone()),
            RecycleProgressState::Failed { message } => Err(Error::Platform {
                message: format!("Windows failed to recycle {}: {message}", path.display()),
            }),
        }
    }
}

impl IFileOperationProgressSink_Impl for RecycleProgressSink_Impl {
    fn PostDeleteItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        delete_result: HRESULT,
        recycled_item: Ref<'_, IShellItem>,
    ) -> windows_core::Result<()> {
        if delete_result.is_err() {
            let source = windows_core::Error::from(delete_result);
            record_progress_failure(
                &self.state,
                format!("Shell delete operation failed: {source}"),
            )?;

            return Err(source);
        }

        let Some(recycled_item) = recycled_item.as_ref() else {
            let message = "Shell permanently deleted the item instead of recycling it";
            record_progress_failure(&self.state, message)?;

            return Err(windows_core::Error::new(E_FAIL, message));
        };

        let recycled_id = match ShellAllocatedString::new(recycled_item) {
            Ok(display_name) => display_name.into_os_string(),
            Err(source) => {
                record_progress_failure(
                    &self.state,
                    format!("Failed to read recycled shell item name: {source}"),
                )?;

                return Err(source);
            }
        };

        let mut state = self.state.lock().map_err(|source| {
            windows_core::Error::new(
                E_FAIL,
                format!(
                    "Recycle progress state was poisoned while recording recycled item: {source}"
                ),
            )
        })?;

        *state = RecycleProgressState::Recycled {
            item_id: recycled_id,
        };

        Ok(())
    }

    fn StartOperations(&self) -> windows_core::Result<()> {
        Ok(())
    }

    fn FinishOperations(&self, _: HRESULT) -> windows_core::Result<()> {
        Ok(())
    }

    fn PreRenameItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        _: &PCWSTR,
    ) -> windows_core::Result<()> {
        Ok(())
    }

    fn PostRenameItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        _: &PCWSTR,
        _: HRESULT,
        _: Ref<'_, IShellItem>,
    ) -> windows_core::Result<()> {
        Ok(())
    }

    fn PreMoveItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        _: Ref<'_, IShellItem>,
        _: &PCWSTR,
    ) -> windows_core::Result<()> {
        Ok(())
    }

    fn PostMoveItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        _: Ref<'_, IShellItem>,
        _: &PCWSTR,
        _: HRESULT,
        _: Ref<'_, IShellItem>,
    ) -> windows_core::Result<()> {
        Ok(())
    }

    fn PreCopyItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        _: Ref<'_, IShellItem>,
        _: &PCWSTR,
    ) -> windows_core::Result<()> {
        Ok(())
    }

    fn PostCopyItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        _: Ref<'_, IShellItem>,
        _: &PCWSTR,
        _: HRESULT,
        _: Ref<'_, IShellItem>,
    ) -> windows_core::Result<()> {
        Ok(())
    }

    fn PreDeleteItem(&self, _: u32, _: Ref<'_, IShellItem>) -> windows_core::Result<()> {
        Ok(())
    }

    fn PreNewItem(&self, _: u32, _: Ref<'_, IShellItem>, _: &PCWSTR) -> windows_core::Result<()> {
        Ok(())
    }

    fn PostNewItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        _: &PCWSTR,
        _: &PCWSTR,
        _: u32,
        _: HRESULT,
        _: Ref<'_, IShellItem>,
    ) -> windows_core::Result<()> {
        Ok(())
    }

    fn UpdateProgress(&self, _: u32, _: u32) -> windows_core::Result<()> {
        Ok(())
    }

    fn ResetTimer(&self) -> windows_core::Result<()> {
        Ok(())
    }

    fn PauseTimer(&self) -> windows_core::Result<()> {
        Ok(())
    }

    fn ResumeTimer(&self) -> windows_core::Result<()> {
        Ok(())
    }
}
