#![expect(
    clippy::inline_always,
    clippy::ref_as_ptr,
    reason = "The COM adapter generated by windows_core::implement triggers these lints."
)]

use std::{
    ffi::OsString,
    os::windows::ffi::OsStringExt,
    path::{Path, PathBuf},
    sync::{Arc, Mutex},
    time::{Duration, SystemTime},
};
use windows::Win32::{
    Foundation::{E_FAIL, FILETIME, PROPERTYKEY},
    Storage::EnhancedStorage::PKEY_FileName,
    System::Com,
    UI::Shell::{
        IFileOperationProgressSink, IFileOperationProgressSink_Impl, IShellItem, IShellItem2,
        PID_DISPLACED_DATE, PID_DISPLACED_FROM, PSGUID_DISPLACED, SHCreateItemFromParsingName,
        SIGDN, SIGDN_DESKTOPABSOLUTEPARSING,
    },
};
use windows_core::{HRESULT, PCWSTR, PWSTR, Ref, implement};

use super::{path::ShellOsStrExt, sta_thread::ComApartment};
use crate::{Error, Result};

const ORIGINAL_LOCATION_PROPERTY_KEY: PROPERTYKEY = PROPERTYKEY {
    fmtid: PSGUID_DISPLACED,
    pid: PID_DISPLACED_FROM,
};
const DELETION_DATE_PROPERTY_KEY: PROPERTYKEY = PROPERTYKEY {
    fmtid: PSGUID_DISPLACED,
    pid: PID_DISPLACED_DATE,
};
const FILE_TIME_TICKS_PER_SECOND: u64 = 10_000_000;
const NANOSECONDS_PER_FILE_TIME_TICK: u64 = 100;
const UNIX_EPOCH_FILE_TIME_TICKS: u64 = 116_444_736_000_000_000;

#[derive(Debug)]
struct ShellString(PWSTR);

impl ShellString {
    fn from_display_name(shell_item: &IShellItem, kind: SIGDN) -> windows_core::Result<Self> {
        // SAFETY: `shell_item` remains valid for the duration of this call and the
        // returned string pointer is released by `ShellString::drop`.
        let pointer = unsafe { shell_item.GetDisplayName(kind)? };
        if pointer.is_null() {
            return Err(windows_core::Error::new(
                E_FAIL,
                "Shell returned a null display name for the recycled item",
            ));
        }

        Ok(Self(pointer))
    }

    fn from_property_string(
        shell_item: &IShellItem2,
        key: &PROPERTYKEY,
    ) -> windows_core::Result<Self> {
        // SAFETY: `shell_item` remains valid for the duration of this call and the
        // returned string pointer is released by `ShellString::drop`.
        let pointer = unsafe { shell_item.GetString(key)? };
        if pointer.is_null() {
            return Err(windows_core::Error::new(
                E_FAIL,
                "Shell returned a null string property for the recycled item",
            ));
        }

        Ok(Self(pointer))
    }

    fn into_os_string(self) -> OsString {
        // SAFETY: `ShellString` is constructed from a non-null
        // Shell string pointer, which is a NUL-terminated UTF-16 string.
        let display_name_wide = unsafe { self.0.as_wide() };

        OsString::from_wide(display_name_wide)
    }
}

impl Drop for ShellString {
    fn drop(&mut self) {
        // SAFETY: `ShellString` stores a Shell-allocated string pointer
        // and this is the only place that releases it.
        unsafe {
            Com::CoTaskMemFree(Some(self.0.as_ptr().cast::<std::ffi::c_void>()));
        }
    }
}

#[derive(Clone, Copy, Debug)]
struct FileTime(u64);

impl FileTime {
    const UNIX_EPOCH: Self = Self(UNIX_EPOCH_FILE_TIME_TICKS);

    fn from_windows(file_time: FILETIME) -> Self {
        Self((u64::from(file_time.dwHighDateTime) << 32) | u64::from(file_time.dwLowDateTime))
    }

    fn to_system_time(&self) -> windows_core::Result<SystemTime> {
        let ticks_from_unix_epoch = self.0.abs_diff(Self::UNIX_EPOCH.0);
        let seconds = ticks_from_unix_epoch / FILE_TIME_TICKS_PER_SECOND;
        let nanoseconds = u32::try_from(
            (ticks_from_unix_epoch % FILE_TIME_TICKS_PER_SECOND) * NANOSECONDS_PER_FILE_TIME_TICK,
        )
        .map_err(|source| {
            windows_core::Error::new(
                E_FAIL,
                format!("Shell returned an invalid recycled item deletion date: {source}"),
            )
        })?;

        let duration = Duration::new(seconds, nanoseconds);
        let system_time = if self.0 >= Self::UNIX_EPOCH.0 {
            SystemTime::UNIX_EPOCH.checked_add(duration)
        } else {
            SystemTime::UNIX_EPOCH.checked_sub(duration)
        };

        system_time.ok_or_else(|| {
            windows_core::Error::new(
                E_FAIL,
                "Shell returned a recycled item deletion date outside the supported time range",
            )
        })
    }
}

#[derive(Debug, Default)]
enum RecycleProgressState {
    #[default]
    Pending,
    Recycled {
        item_id: OsString,
    },
    Failed {
        message: String,
    },
}

#[derive(Debug)]
pub(super) struct RecycledItem {
    pub(super) id: OsString,
    pub(super) original_name: OsString,
    pub(super) original_parent: PathBuf,
    pub(super) discarded_at: SystemTime,
}

fn record_progress_failure(
    state: &Arc<Mutex<RecycleProgressState>>,
    failure: impl Into<String>,
) -> windows_core::Result<()> {
    let mut state = state.lock().map_err(|source| {
        windows_core::Error::new(
            E_FAIL,
            format!("Recycle progress state was poisoned while recording failure: {source}"),
        )
    })?;

    *state = RecycleProgressState::Failed {
        message: failure.into(),
    };

    Ok(())
}

#[implement(IFileOperationProgressSink)]
#[derive(Debug)]
pub(super) struct RecycleProgressSink {
    state: Arc<Mutex<RecycleProgressState>>,
}

impl RecycleProgressSink {
    pub(super) fn new() -> Self {
        Self {
            state: Arc::new(Mutex::new(RecycleProgressState::default())),
        }
    }

    pub(super) fn to_file_operation_progress_sink(&self) -> IFileOperationProgressSink {
        Self {
            state: Arc::clone(&self.state),
        }
        .into()
    }

    pub(super) fn failure_message(&self) -> windows_core::Result<Option<String>> {
        let state = self.state.lock().map_err(|source| {
            windows_core::Error::new(
                E_FAIL,
                format!("Recycle progress state was poisoned while reading failure: {source}"),
            )
        })?;

        match &*state {
            RecycleProgressState::Failed { message } => Ok(Some(message.clone())),
            _ => Ok(None),
        }
    }

    pub(super) fn recycled_item(
        &self,
        _com_apartment: &ComApartment,
        path: &Path,
    ) -> Result<RecycledItem> {
        let item_id = {
            let state = self.state.lock().map_err(|source| Error::Platform {
                message: format!(
                    "Recycle progress state was poisoned for {}: {source}",
                    path.display()
                ),
            })?;

            match &*state {
                RecycleProgressState::Pending => Err(Error::Platform {
                    message: format!(
                        "Windows did not return a recycled shell item for {}",
                        path.display()
                    ),
                }),
                RecycleProgressState::Recycled { item_id } => Ok(item_id.clone()),
                RecycleProgressState::Failed { message } => Err(Error::Platform {
                    message: format!("Windows failed to recycle {}: {message}", path.display()),
                }),
            }?
        };

        let metadata_error = |source: windows_core::Error| Error::Platform {
            message: format!(
                "Failed to read Windows recycled item metadata for {}: {source}",
                path.display()
            ),
        };

        let wide_item_id = item_id.as_os_str().wide_path().map_err(|source| {
            metadata_error(windows_core::Error::new(
                E_FAIL,
                format!("Shell returned an invalid recycled item id: {source}"),
            ))
        })?;

        // SAFETY: `wide_item_id` is NUL-terminated and remains valid for the
        // duration of this call.
        let shell_item: IShellItem2 =
            unsafe { SHCreateItemFromParsingName(PCWSTR(wide_item_id.as_ptr()), None) }
                .map_err(metadata_error)?;
        let original_name = ShellString::from_property_string(&shell_item, &PKEY_FileName)
            .map_err(metadata_error)?
            .into_os_string();

        let original_parent =
            ShellString::from_property_string(&shell_item, &ORIGINAL_LOCATION_PROPERTY_KEY)
                .map_err(metadata_error)?
                .into_os_string();

        // SAFETY: `shell_item` remains valid for the duration of this call. The
        // property key is static.
        let deletion_date = unsafe { shell_item.GetFileTime(&DELETION_DATE_PROPERTY_KEY) }
            .map_err(metadata_error)?;
        let discarded_at = FileTime::from_windows(deletion_date)
            .to_system_time()
            .map_err(metadata_error)?;

        Ok(RecycledItem {
            id: item_id,
            original_name,
            original_parent: PathBuf::from(original_parent),
            discarded_at,
        })
    }
}

impl IFileOperationProgressSink_Impl for RecycleProgressSink_Impl {
    fn PostDeleteItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        delete_result: HRESULT,
        recycled_item: Ref<'_, IShellItem>,
    ) -> windows_core::Result<()> {
        if delete_result.is_err() {
            let source = windows_core::Error::from(delete_result);
            record_progress_failure(
                &self.state,
                format!("Shell delete operation failed: {source}"),
            )?;

            return Err(source);
        }

        let Some(recycled_item) = recycled_item.as_ref() else {
            let message = "Shell permanently deleted the item instead of recycling it";
            record_progress_failure(&self.state, message)?;

            return Err(windows_core::Error::new(E_FAIL, message));
        };

        let recycled_id =
            match ShellString::from_display_name(recycled_item, SIGDN_DESKTOPABSOLUTEPARSING) {
                Ok(display_name) => display_name.into_os_string(),
                Err(source) => {
                    record_progress_failure(
                        &self.state,
                        format!("Failed to read recycled shell item name: {source}"),
                    )?;

                    return Err(source);
                }
            };

        let mut state = self.state.lock().map_err(|source| {
            windows_core::Error::new(
                E_FAIL,
                format!(
                    "Recycle progress state was poisoned while recording recycled item: {source}"
                ),
            )
        })?;

        *state = RecycleProgressState::Recycled {
            item_id: recycled_id,
        };

        Ok(())
    }

    fn StartOperations(&self) -> windows_core::Result<()> {
        Ok(())
    }

    fn FinishOperations(&self, _: HRESULT) -> windows_core::Result<()> {
        Ok(())
    }

    fn PreRenameItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        _: &PCWSTR,
    ) -> windows_core::Result<()> {
        Ok(())
    }

    fn PostRenameItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        _: &PCWSTR,
        _: HRESULT,
        _: Ref<'_, IShellItem>,
    ) -> windows_core::Result<()> {
        Ok(())
    }

    fn PreMoveItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        _: Ref<'_, IShellItem>,
        _: &PCWSTR,
    ) -> windows_core::Result<()> {
        Ok(())
    }

    fn PostMoveItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        _: Ref<'_, IShellItem>,
        _: &PCWSTR,
        _: HRESULT,
        _: Ref<'_, IShellItem>,
    ) -> windows_core::Result<()> {
        Ok(())
    }

    fn PreCopyItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        _: Ref<'_, IShellItem>,
        _: &PCWSTR,
    ) -> windows_core::Result<()> {
        Ok(())
    }

    fn PostCopyItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        _: Ref<'_, IShellItem>,
        _: &PCWSTR,
        _: HRESULT,
        _: Ref<'_, IShellItem>,
    ) -> windows_core::Result<()> {
        Ok(())
    }

    fn PreDeleteItem(&self, _: u32, _: Ref<'_, IShellItem>) -> windows_core::Result<()> {
        Ok(())
    }

    fn PreNewItem(&self, _: u32, _: Ref<'_, IShellItem>, _: &PCWSTR) -> windows_core::Result<()> {
        Ok(())
    }

    fn PostNewItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        _: &PCWSTR,
        _: &PCWSTR,
        _: u32,
        _: HRESULT,
        _: Ref<'_, IShellItem>,
    ) -> windows_core::Result<()> {
        Ok(())
    }

    fn UpdateProgress(&self, _: u32, _: u32) -> windows_core::Result<()> {
        Ok(())
    }

    fn ResetTimer(&self) -> windows_core::Result<()> {
        Ok(())
    }

    fn PauseTimer(&self) -> windows_core::Result<()> {
        Ok(())
    }

    fn ResumeTimer(&self) -> windows_core::Result<()> {
        Ok(())
    }
}
