#![expect(
    clippy::inline_always,
    clippy::ref_as_ptr,
    reason = "The COM adapter generated by windows_core::implement triggers these lints."
)]

use std::{
    ffi::OsString,
    path::{Path, PathBuf},
    sync::{Arc, Mutex},
    time::SystemTime,
};
use windows::Win32::{
    Foundation::{E_FAIL, PROPERTYKEY},
    Storage::EnhancedStorage::PKEY_FileName,
    UI::Shell::{
        FOF_NO_CONNECTED_ELEMENTS, FOF_NOERRORUI, FOF_SILENT, FOF_WANTNUKEWARNING,
        FOFX_ADDUNDORECORD, FOFX_EARLYFAILURE, FOFX_RECYCLEONDELETE, IFileOperation,
        IFileOperationProgressSink, IFileOperationProgressSink_Impl, IShellItem, IShellItem2,
        PID_DISPLACED_DATE, PID_DISPLACED_FROM, PSGUID_DISPLACED, SIGDN_DESKTOPABSOLUTEPARSING,
    },
};
use windows_core::{HRESULT, PCWSTR, Ref, implement};

use super::{
    path::ShellOsStrExt,
    shell::{FileTime, ShellContext, ShellString},
};
use crate::{Error, Result};

const ORIGINAL_LOCATION_PROPERTY_KEY: PROPERTYKEY = PROPERTYKEY {
    fmtid: PSGUID_DISPLACED,
    pid: PID_DISPLACED_FROM,
};
const DELETION_DATE_PROPERTY_KEY: PROPERTYKEY = PROPERTYKEY {
    fmtid: PSGUID_DISPLACED,
    pid: PID_DISPLACED_DATE,
};

#[derive(Debug)]
pub(super) struct RecycleOperation {
    operation: IFileOperation,
}

impl RecycleOperation {
    pub(super) fn new(shell_context: &ShellContext, path: &Path) -> Result<Self> {
        let operation = Self {
            operation: shell_context.file_operation(path)?,
        };

        operation.set_recycle_flags(path)?;

        Ok(operation)
    }

    fn set_recycle_flags(&self, path: &Path) -> Result<()> {
        let operation_flags = FOFX_RECYCLEONDELETE
            | FOFX_ADDUNDORECORD
            | FOFX_EARLYFAILURE
            | FOF_NOERRORUI
            | FOF_NO_CONNECTED_ELEMENTS
            | FOF_SILENT
            | FOF_WANTNUKEWARNING;

        // SAFETY: `self.operation` comes from a successful `CoCreateInstance` call.
        // `SetOperationFlags` only reads the interface pointer for this call.
        unsafe { self.operation.SetOperationFlags(operation_flags) }.map_err(|source| {
            Error::Platform {
                message: format!(
                    "Failed to configure Windows recycle operation for {}: {source}",
                    path.display()
                ),
            }
        })
    }

    pub(super) fn queue_delete(
        &self,
        path: &Path,
        shell_item: &IShellItem,
        sink: &IFileOperationProgressSink,
    ) -> Result<()> {
        // SAFETY: `self.operation` and `shell_item` are valid COM interfaces.
        // `sink` remains alive for the duration of the queued operation.
        unsafe { self.operation.DeleteItem(shell_item, sink) }.map_err(|source| Error::Platform {
            message: format!(
                "Failed to queue Windows recycle operation for {}: {source}",
                path.display()
            ),
        })
    }

    pub(super) fn execute(&self, path: &Path, sink: &RecycleProgressSink) -> Result<()> {
        // SAFETY: `self.operation` comes from a successful `CoCreateInstance` call.
        // The queued item and progress sink remain alive for the duration of this call.
        let operation_result = unsafe { self.operation.PerformOperations() };

        // SAFETY: `self.operation` comes from a successful `CoCreateInstance` call.
        // It remains valid after `PerformOperations` returns.
        let operation_aborted = unsafe { self.operation.GetAnyOperationsAborted() }
            .map(windows_core::BOOL::as_bool)
            .map_err(|source| Error::Platform {
                message: format!(
                    "Failed to inspect Windows recycle operation for {}: {source}",
                    path.display()
                ),
            });
        let operation_aborted = match operation_aborted {
            Ok(operation_aborted) => operation_aborted,
            Err(inspect_error) => match operation_result {
                Ok(()) => return Err(inspect_error),
                Err(source) => {
                    if let RecycleProgressState::Failed { message } = sink.status().map_err(
                        |progress_error| Error::Platform {
                            message: format!(
                                "Failed to perform Windows recycle operation for {}; recycle progress state was poisoned: {progress_error}; operation error: {source}",
                                path.display()
                            ),
                        },
                    )?
                    {
                        return Err(Error::Platform {
                            message: format!(
                                "Failed to perform Windows recycle operation for {}: {message}; failed to inspect aborted state: {inspect_error}",
                                path.display()
                            ),
                        });
                    }

                    return Err(Error::Platform {
                        message: format!(
                            "Failed to perform Windows recycle operation for {}: {source}; failed to inspect aborted state: {inspect_error}",
                            path.display()
                        ),
                    });
                }
            },
        };

        match operation_result {
            Ok(()) if operation_aborted => Err(Error::Platform {
                message: format!(
                    "Windows recycle operation was aborted for {}",
                    path.display()
                ),
            }),
            Ok(()) => Ok(()),
            Err(source) => {
                if let RecycleProgressState::Failed { message } = sink.status().map_err(
                    |progress_error| Error::Platform {
                        message: format!(
                            "Failed to perform Windows recycle operation for {}; recycle progress state was poisoned: {progress_error}; operation error: {source}",
                            path.display()
                        ),
                    },
                )?
                {
                    return Err(Error::Platform {
                        message: format!(
                            "Failed to perform Windows recycle operation for {}: {message}",
                            path.display()
                        ),
                    });
                }

                if operation_aborted {
                    return Err(Error::Platform {
                        message: format!(
                            "Windows recycle operation was aborted for {}: {source}",
                            path.display()
                        ),
                    });
                }

                Err(Error::Platform {
                    message: format!(
                        "Failed to perform Windows recycle operation for {}: {source}",
                        path.display()
                    ),
                })
            }
        }
    }
}

#[derive(Clone, Debug, Default)]
enum RecycleProgressState {
    #[default]
    Pending,
    Recycled {
        item_id: OsString,
    },
    Failed {
        message: String,
    },
}

#[derive(Clone, Debug, Default)]
struct RecycleProgress(Arc<Mutex<RecycleProgressState>>);

impl RecycleProgress {
    fn status(&self) -> windows_core::Result<RecycleProgressState> {
        let state = self.0.lock().map_err(|source| {
            windows_core::Error::new(
                E_FAIL,
                format!("Recycle progress state was poisoned while reading status: {source}"),
            )
        })?;

        Ok(state.clone())
    }

    fn record_recycled(&self, item_id: OsString) -> windows_core::Result<()> {
        let mut state = self.0.lock().map_err(|source| {
            windows_core::Error::new(
                E_FAIL,
                format!(
                    "Recycle progress state was poisoned while recording recycled item: {source}"
                ),
            )
        })?;

        *state = RecycleProgressState::Recycled { item_id };

        Ok(())
    }

    fn record_failed(&self, failure: impl Into<String>) -> windows_core::Result<()> {
        let mut state = self.0.lock().map_err(|source| {
            windows_core::Error::new(
                E_FAIL,
                format!("Recycle progress state was poisoned while recording failure: {source}"),
            )
        })?;

        *state = RecycleProgressState::Failed {
            message: failure.into(),
        };

        Ok(())
    }
}

#[derive(Debug)]
pub(super) struct RecycledItem {
    pub(super) id: OsString,
    pub(super) original_name: OsString,
    pub(super) original_parent: PathBuf,
    pub(super) discarded_at: SystemTime,
}

impl RecycledItem {
    pub(super) fn from_progress(
        shell_context: &ShellContext,
        sink: &RecycleProgressSink,
        path: &Path,
    ) -> Result<Self> {
        let item_id = match sink.status().map_err(|source| Error::Platform {
            message: format!(
                "Failed to read Windows recycle progress status for {}: {source}",
                path.display()
            ),
        })? {
            RecycleProgressState::Pending => {
                return Err(Error::Platform {
                    message: format!(
                        "Windows did not return a recycled shell item for {}",
                        path.display()
                    ),
                });
            }
            RecycleProgressState::Recycled { item_id } => item_id,
            RecycleProgressState::Failed { message } => {
                return Err(Error::Platform {
                    message: format!("Windows failed to recycle {}: {message}", path.display()),
                });
            }
        };
        let metadata_error = |source: windows_core::Error| Error::Platform {
            message: format!(
                "Failed to read Windows recycled item metadata for {}: {source}",
                path.display()
            ),
        };

        let wide_item_id = item_id.as_os_str().wide_path().map_err(|source| {
            metadata_error(windows_core::Error::new(
                E_FAIL,
                format!("Shell returned an invalid recycled item id: {source}"),
            ))
        })?;

        let shell_item = shell_context
            .item_from_wide_path::<IShellItem2>(&wide_item_id)
            .map_err(metadata_error)?;
        let original_name = ShellString::from_property_string(&shell_item, &PKEY_FileName)
            .map_err(metadata_error)?
            .into_os_string();

        let original_parent =
            ShellString::from_property_string(&shell_item, &ORIGINAL_LOCATION_PROPERTY_KEY)
                .map_err(metadata_error)?
                .into_os_string();

        // SAFETY: `shell_item` remains valid for the duration of this call. The
        // property key is static.
        let deletion_date = unsafe { shell_item.GetFileTime(&DELETION_DATE_PROPERTY_KEY) }
            .map_err(metadata_error)?;
        let discarded_at = FileTime::from_windows(deletion_date)
            .to_system_time()
            .map_err(metadata_error)?;

        Ok(RecycledItem {
            id: item_id,
            original_name,
            original_parent: PathBuf::from(original_parent),
            discarded_at,
        })
    }
}

#[implement(IFileOperationProgressSink)]
#[derive(Debug)]
pub(super) struct RecycleProgressSink {
    progress: RecycleProgress,
}

impl RecycleProgressSink {
    pub(super) fn new() -> Self {
        Self {
            progress: RecycleProgress::default(),
        }
    }

    pub(super) fn to_file_operation_sink(&self) -> IFileOperationProgressSink {
        Self {
            progress: self.progress.clone(),
        }
        .into()
    }

    fn status(&self) -> windows_core::Result<RecycleProgressState> {
        self.progress.status()
    }
}

impl IFileOperationProgressSink_Impl for RecycleProgressSink_Impl {
    fn PostDeleteItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        delete_result: HRESULT,
        recycled_item: Ref<'_, IShellItem>,
    ) -> windows_core::Result<()> {
        if delete_result.is_err() {
            let source = windows_core::Error::from(delete_result);
            self.progress
                .record_failed(format!("Shell delete operation failed: {source}"))?;

            return Err(source);
        }

        let Some(recycled_item) = recycled_item.as_ref() else {
            let message = "Shell permanently deleted the item instead of recycling it";
            self.progress.record_failed(message)?;

            return Err(windows_core::Error::new(E_FAIL, message));
        };

        let recycled_id =
            match ShellString::from_display_name(recycled_item, SIGDN_DESKTOPABSOLUTEPARSING) {
                Ok(display_name) => display_name.into_os_string(),
                Err(source) => {
                    self.progress.record_failed(format!(
                        "Failed to read recycled shell item name: {source}"
                    ))?;

                    return Err(source);
                }
            };

        self.progress.record_recycled(recycled_id)?;

        Ok(())
    }

    fn StartOperations(&self) -> windows_core::Result<()> {
        Ok(())
    }

    fn FinishOperations(&self, _: HRESULT) -> windows_core::Result<()> {
        Ok(())
    }

    fn PreRenameItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        _: &PCWSTR,
    ) -> windows_core::Result<()> {
        Ok(())
    }

    fn PostRenameItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        _: &PCWSTR,
        _: HRESULT,
        _: Ref<'_, IShellItem>,
    ) -> windows_core::Result<()> {
        Ok(())
    }

    fn PreMoveItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        _: Ref<'_, IShellItem>,
        _: &PCWSTR,
    ) -> windows_core::Result<()> {
        Ok(())
    }

    fn PostMoveItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        _: Ref<'_, IShellItem>,
        _: &PCWSTR,
        _: HRESULT,
        _: Ref<'_, IShellItem>,
    ) -> windows_core::Result<()> {
        Ok(())
    }

    fn PreCopyItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        _: Ref<'_, IShellItem>,
        _: &PCWSTR,
    ) -> windows_core::Result<()> {
        Ok(())
    }

    fn PostCopyItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        _: Ref<'_, IShellItem>,
        _: &PCWSTR,
        _: HRESULT,
        _: Ref<'_, IShellItem>,
    ) -> windows_core::Result<()> {
        Ok(())
    }

    fn PreDeleteItem(&self, _: u32, _: Ref<'_, IShellItem>) -> windows_core::Result<()> {
        Ok(())
    }

    fn PreNewItem(&self, _: u32, _: Ref<'_, IShellItem>, _: &PCWSTR) -> windows_core::Result<()> {
        Ok(())
    }

    fn PostNewItem(
        &self,
        _: u32,
        _: Ref<'_, IShellItem>,
        _: &PCWSTR,
        _: &PCWSTR,
        _: u32,
        _: HRESULT,
        _: Ref<'_, IShellItem>,
    ) -> windows_core::Result<()> {
        Ok(())
    }

    fn UpdateProgress(&self, _: u32, _: u32) -> windows_core::Result<()> {
        Ok(())
    }

    fn ResetTimer(&self) -> windows_core::Result<()> {
        Ok(())
    }

    fn PauseTimer(&self) -> windows_core::Result<()> {
        Ok(())
    }

    fn ResumeTimer(&self) -> windows_core::Result<()> {
        Ok(())
    }
}
